/**
 * Notifications (Phase 6). In-app bell items generated by runSweep() (low stock,
 * debt/payable reminders). Broadcast items (userId null) are visible to everyone.
 */
import { Router } from "express";
import { Prisma } from "@prisma/client";
import { prisma } from "../lib/prisma";
import { requireAuth } from "../middleware/auth";
import { runSweep } from "../lib/notify";

const router = Router();
router.use(requireAuth);

const mine = (userId: string): Prisma.NotificationWhereInput => ({ OR: [{ userId: null }, { userId }] });

/** GET /notifications?unread=1 */
router.get("/", async (req, res, next) => {
  try {
    const where: Prisma.NotificationWhereInput = { ...mine(req.user!.id), ...(req.query.unread === "1" ? { isRead: false } : {}) };
    const notifications = await prisma.notification.findMany({ where, orderBy: { createdAt: "desc" }, take: 60 });
    res.json({ ok: true, data: { notifications } });
  } catch (err) {
    next(err);
  }
});

/** GET /notifications/unread-count */
router.get("/unread-count", async (req, res, next) => {
  try {
    const count = await prisma.notification.count({ where: { ...mine(req.user!.id), isRead: false } });
    res.json({ ok: true, data: { count } });
  } catch (err) {
    next(err);
  }
});

/** POST /notifications/:id/read */
router.post("/:id/read", async (req, res, next) => {
  try {
    await prisma.notification.updateMany({ where: { id: req.params.id, ...mine(req.user!.id) }, data: { isRead: true } });
    res.json({ ok: true, data: { message: "Marked read" } });
  } catch (err) {
    next(err);
  }
});

/** POST /notifications/read-all */
router.post("/read-all", async (req, res, next) => {
  try {
    await prisma.notification.updateMany({ where: { ...mine(req.user!.id), isRead: false }, data: { isRead: true } });
    res.json({ ok: true, data: { message: "All caught up" } });
  } catch (err) {
    next(err);
  }
});

/** POST /notifications/sweep — regenerate alerts now (deduped) */
router.post("/sweep", async (_req, res, next) => {
  try {
    const result = await runSweep();
    res.json({ ok: true, data: result });
  } catch (err) {
    next(err);
  }
});

export default router;
